# Configuración de servicios con Docker Compose
version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPassword.Seguro123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./scripts:/scripts:ro
      - ./src/db/sp:/sp:ro    # monta /src/db/sp como /sp
    healthcheck:
      test: ["CMD-SHELL","/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${MSSQL_SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: api-expedientes
    env_file: .env
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  mssql_data:
